### ISSUE TITLE
Hello world does not compile

### ISSUE THREAD

**Issue by matthewp** [matthewmueller/joy#53]
Hello, I followed the instructions from running the `joy` command the first time and get this error message:

```js
cannot find package "../../../matt/go/src/github.com/matthewmueller/joy/internal/runtime" in:
	/Users/matt/go/src/github.com/matthewmueller/joy/internal/runtime
   ⨯ error building packages: parse error: load error: unable to load the go package: couldn't load packages due to errors: ../../../matt/go/src/github.com/matthewmueller/joy/internal/runtime
```

**Comment by beaucollins** [comment]
Same here for `joy run main.go`. Unfortunately my username is not `matt`:

```
   ⨯ error downloading headless chrome: error making directory: mkdir /Users/matt: permission denied
```

**Comment by peterhellberg** [comment]
I had the exact same issue as @beaucollins and was about to open a new issue :)

**Comment by matthewmueller** [comment]
oh wow! haha that's weird. will fix asap

**Comment by beaucollins** [comment]
@matthewmueller for reproducibility purposes I downloaded the latest release and put `joy` in my path at `~/bin/joy`.

**Comment by matthewp** [comment]
@matthewmueller no, `joy main.go` gives me the error in the OP.

**Comment by beaucollins** [comment]
My `joy main.go` produces the same as @matthewp

**Comment by matthewp** [comment]
@matthewmueller no problem! If you could point at where you think the problem *might* be maybe I can try while you're sleeping.

**Comment by raisedadead** [comment]
```sh
~/DEV/test 29s
❯ joy run main.go
   • downloading headless chrome (this only needs to be done once)
   ⨯ error downloading headless chrome: error making directory: mkdir /Users/matt: permission denied
~/DEV/test
❯ joy main.go
   ⨯ error building code: parse error: load error: GOPATH not set
```

**Comment by matthewp** [comment]
@raisedadead That's a different issue (well, maybe 2 issues). joy does assume that you have GOPATH setup, which is a reasonable expectation for a Go compiler.

**Comment by raisedadead** [comment]
Yup, I am up for adding that to the instructions in readme. PR on its way.

**Comment by prettymuchbryce** [comment]
I would agree that it's reasonable, but keep in mind that starting at Go 1.8 there is a default GOPATH. It may be ideal to use that in the case that the GOPATH is not defined.

https://rakyll.org/default-gopath/

**Comment by matthewmueller** [comment]
Hey folks, sorry for the install issues. The latest release 0.1.4 should address these problems. Just like in Go, `$GOPATH` is not required for simple programs (like this hello world).

It's when you start pulling in dependencies, you'll need the Go toolchain setup.

Could you please try again and let me know if there are any issues?

**Comment by 1l0** [comment]
Joy version: https://github.com/matthewmueller/joy/commit/962d3acf84eb95307defde245f87aff59a62e3a7
Within ```_examples/01-hello-world``` directory:
```sh
$ joy run main.go 
hello world!
   ⨯ error flushing            error=missing stream name
$ joy main.go
;(function() {
  var pkg = {};
  pkg["main"] = (function() {
    function main () {
      console.log.apply(console.log, ["hello world!"])
    };
    return {
      main: main
    };
  })();
  return pkg["main"].main();
})()
   ⨯ error flushing            error=missing stream name
```

**Comment by matthewmueller** [comment]
ahh yah, this is fixed on master, will push a release tomorrow!

**Comment by raisedadead** [comment]
Installed again like so:
```
❯ curl -sfL https://raw.githubusercontent.com/matthewmueller/joy/master/install.sh | sh
```
and then:
```
~/DEV/test
❯ joy run main.go
   • downloading headless chrome (this only needs to be done once)
   ⨯ parse error: load error: GOPATH not set
```

The headless chrome now passes, but the GOPATH complaint is still present.

**Comment by raisedadead** [comment]
Also
```
~/DEV/test
❯ joy main.go
   ⨯ error building code: parse error: load error: GOPATH not set
```

**Comment by erbesharat** [comment]
I have a similar error, everything works fine and it returns right code, but it also returns an error too. I'm using latest version pulled from master.
```shell
⨯ error flushing            error=missing stream name
```

**Comment by matthewmueller** [comment]
@erbesharat hey this should be fixed on the latest, could you please `go get` again?

**Comment by erbesharat** [comment]
@matthewmueller still have the issue
```
 erbesharat@debian >> joy version                                    
   • master                   
   ⨯ error flushing            error=missing stream name
```

**Comment by 1l0** [comment]
The error still remains.
```
$ go get -u github.com/matthewmueller/joy/cmd/joy
$ joy run main.go 
hello world!
   ⨯ error flushing            error=missing stream name
$ joy version
   • master                   
   ⨯ error flushing            error=missing stream name
```

**Comment by tryy3** [comment]
@matthewmueller if it helps, the stream name error comes from your firehose package.
Becuase https://github.com/matthewmueller/joy/blob/master/internal/stats/stats.go#L36 on that line you initialize the firehose and set the stream name to an environment variable.
But if you use go get/git to download joy and install it, you wont have JOY_AWS_FIREHOSE_STREAM variable set, in which case the firehose package complains.
