### ISSUE TITLE
Adjust font-weight on website

### ISSUE THREAD

**Issue by rgfoley** [matthewmueller/joy#64]
First off, the library is really interesting. I was reading through the FAQ, however, and I noticed that the text on the website (at least in the latest Firefox build for Windows) has some really unusual distortion. I've attached two images illustrating how it is vs. a potential fix.

It seems the font-weight doesn't play nicely with some of the font-family values that are specified.

![current](https://user-images.githubusercontent.com/7256749/33952147-f15c2ea2-dffe-11e7-8dcc-b597c7fb24da.png)
![fixed](https://user-images.githubusercontent.com/7256749/33952146-f1486642-dffe-11e7-9599-b093d1b79d2a.png)

**Comment by matthewmueller** [comment]
Woah, thanks for bringing this up. Right now I'm just using the default system fonts, but maybe that font-weight isn't well supported on the windows font. 

Could you try `font-weight: 200` to see if that fixes the problem?

**Comment by rgfoley** [comment]
It doesn't seem to fix it, however I noticed that (on my system) the first font it falls back to is "Segoe UI". When I set the font directly to "Segoe UI Light" (which is what weight 300 maps to) it seems it has trouble at that particular font-size. It only appears to be an issue on my Windows 7 system (Windows 10 looks fine without changing anything).

**Comment by matthewmueller** [comment]
Hmm, that's interesting. I think I'll keep this open for now to see if anyone else runs into it. In the meantime, I've pushed a version with `Segoe UI Light` in front of `Segoe`. Does that improve it or is it the same?

**Comment by rgfoley** [comment]
It is still the same. I think having the font-weight at 300 effectively is the same as having it set to Light. Regular Segoe UI looks fine, but doesn't have quite the same style (as pictured above).
